Follow vint

diff --git a/home/.vim/vimrc b/home/.vim/vimrc
--- a/home/.vim/vimrc
+++ b/home/.vim/vimrc
@@ -3,19 +3,19 @@
 " Author:   Alisue <lambdalisue@hashnote.net>
 " URI:      http://hashnote.net/
 " Platform: Linux, Mac OS X
-" 
+"
 
 " skip if the live Vim is vim-tiny or vim-small
 if !1 | finish | endif
 
 " platform recognition
-let s:is_windows = has("win16") || has("win32") || has("win64")
-let s:is_darwin = has("mac") || has("macunix") || has("gui_macvim")
+let s:is_windows = has('win16') || has('win32') || has('win64')
+let s:is_darwin = has('mac') || has('macunix') || has('gui_macvim')
 let s:is_linux = !s:is_windows && !s:is_darwin
 if s:is_windows
-  let s:delimiter = ";"
+  let s:delimiter = ';'
 else
-  let s:delimiter = ":"
+  let s:delimiter = ':'
 endif
 
 " reset settings for reloading vimrc
@@ -41,9 +41,9 @@ function! s:add_pythonpath(path)
 endfunction
 
 function! s:load_source(path)
-  let path = fnamemodify(expand(a:path), ":p")
+  let path = fnamemodify(expand(a:path), ':p')
   if filereadable(path)
-    execute "source" path
+    execute 'source' path
     return 1
   endif
   return 0
@@ -51,62 +51,62 @@ endfunction
 " }}}
 
 " environmental variables {{{
-if has("nvim")
+if has('nvim')
   set shell=/bin/zsh
 else
   set shell=/bin/bash
 endif
 
-call s:add_path("/usr/local/texlive/2013/bin/x86_64-linux")
-call s:add_path("/usr/local/texlive/2013/bin/x86_64-darwin")
-call s:add_path(expand("~/.pyenv/bin"))
-call s:add_path(expand("~/.plenv/bin"))
-call s:add_path(expand("~/.rbenv/bin"))
-call s:add_path(expand("~/.ndenv/bin"))
-call s:add_path(expand("~/.pyenv/shims"))
-call s:add_path(expand("~/.plenv/shims"))
-call s:add_path(expand("~/.rbenv/shims"))
-call s:add_path(expand("~/.ndenv/shims"))
-call s:add_path(expand("~/.anyenv/envs/pyenv/bin"))
-call s:add_path(expand("~/.anyenv/envs/plenv/bin"))
-call s:add_path(expand("~/.anyenv/envs/rbenv/bin"))
-call s:add_path(expand("~/.anyenv/envs/ndenv/bin"))
-call s:add_path(expand("~/.anyenv/envs/pyenv/shims"))
-call s:add_path(expand("~/.anyenv/envs/plenv/shims"))
-call s:add_path(expand("~/.anyenv/envs/rbenv/shims"))
-call s:add_path(expand("~/.anyenv/envs/ndenv/shims"))
-call s:add_path(expand("~/.cabal/bin"))
-call s:add_path(expand("~/.vim/bundle/vim-themis/bin"))
+call s:add_path('/usr/local/texlive/2013/bin/x86_64-linux')
+call s:add_path('/usr/local/texlive/2013/bin/x86_64-darwin')
+call s:add_path(expand('~/.pyenv/bin'))
+call s:add_path(expand('~/.plenv/bin'))
+call s:add_path(expand('~/.rbenv/bin'))
+call s:add_path(expand('~/.ndenv/bin'))
+call s:add_path(expand('~/.pyenv/shims'))
+call s:add_path(expand('~/.plenv/shims'))
+call s:add_path(expand('~/.rbenv/shims'))
+call s:add_path(expand('~/.ndenv/shims'))
+call s:add_path(expand('~/.anyenv/envs/pyenv/bin'))
+call s:add_path(expand('~/.anyenv/envs/plenv/bin'))
+call s:add_path(expand('~/.anyenv/envs/rbenv/bin'))
+call s:add_path(expand('~/.anyenv/envs/ndenv/bin'))
+call s:add_path(expand('~/.anyenv/envs/pyenv/shims'))
+call s:add_path(expand('~/.anyenv/envs/plenv/shims'))
+call s:add_path(expand('~/.anyenv/envs/rbenv/shims'))
+call s:add_path(expand('~/.anyenv/envs/ndenv/shims'))
+call s:add_path(expand('~/.cabal/bin'))
+call s:add_path(expand('~/.vim/bundle/vim-themis/bin'))
 
-let $MY_VIMRUNTIME = expand("~/.vim")
-let $MYVIMRC = resolve($MY_VIMRUNTIME."/vimrc")
-let $MYGVIMRC = resolve($MY_VIMRUNTIME."/gvimrc")
+let $MY_VIMRUNTIME = expand('~/.vim')
+let $MYVIMRC = resolve($MY_VIMRUNTIME.'/vimrc')
+let $MYGVIMRC = resolve($MY_VIMRUNTIME.'/gvimrc')
 
-if isdirectory(expand("~/.anyenv/envs/pyenv"))
-  let $PYENV_ROOT = expand("~/.anyenv/envs/pyenv")
-elseif isdirectory(expand("~/.pyenv"))
-  let $PYENV_ROOT = expand("~/.pyenv")
+if isdirectory(expand('~/.anyenv/envs/pyenv'))
+  let $PYENV_ROOT = expand('~/.anyenv/envs/pyenv')
+elseif isdirectory(expand('~/.pyenv'))
+  let $PYENV_ROOT = expand('~/.pyenv')
 endif
 " }}}
 
 " fundemental config {{{
 
-" history ":" commands and search patterns as much as possible (max: 10000)
+" history ':' commands and search patterns as much as possible (max: 10000)
 set history=10000
 
 " define <Leader> and <LocalLeader>
-let g:mapleader = ";"
-let g:maplocalleader = ","
+let g:mapleader = ';'
+let g:maplocalleader = ','
 " remove any existing keymap for leader and localleader
 nnoremap ; <Nop>
 xnoremap ; <Nop>
 nnoremap , <Nop>
 xnoremap , <Nop>
 
-if !has("gui_running")
+if !has('gui_running')
   set ttyfast         " enable fast terminal connection
-  if exists("&ttyscroll")
-    " neovim does not have "ttyscroll"
+  if exists('&ttyscroll')
+    " neovim does not have 'ttyscroll"
     set ttyscroll=3     " the maximum number of lines for scrolling.
                         " use small value here to prefer redraw the screen
                         " instead of scrolling
@@ -142,15 +142,15 @@ set helplang=en,ja
 " cjk - ignore spell check on Asian characters (China, Japan, Korea)
 set nospell
 set spelllang=en_us,cjk
-let &spellfile=expand("~/Copy/Apps/Vim/system/spellfile.utf-8.add")
+let &spellfile=expand('~/Copy/Apps/Vim/system/spellfile.utf-8.add')
 
 " prefer UTF-8
-scriptencoding utf-8
-if has("multi_byte")
-  if has("vim_starting") || !has('nvim')
+if has('multi_byte')
+  if has('vim_starting') || !has('nvim')
     set encoding=utf-8
     set termencoding=utf-8
   endif
+  scriptencoding utf-8
   set fileencodings=ucs-bom,utf-8,euc-jp,iso-2022-jp,cp932,utf-16,utf-16le
   set fileformats=unix,dos,mac
 endif
@@ -168,8 +168,8 @@ set hlsearch        " highlight found terms
 set keywordprg=:help
 
 " automatically escape / or ?
-cnoremap <expr> / getcmdtype() == "/" ? "\/" : "/"
-cnoremap <expr> ? getcmdtype() == "?" ? "\?" : "?"
+cnoremap <expr> / getcmdtype() == '/' ? '\/' : '/'
+cnoremap <expr> ? getcmdtype() == '?' ? '\?' : '?'
 
 " remove highlight with pressing ESC twice
 nnoremap <silent> <Esc><Esc> :<C-u>nohlsearch<CR>
@@ -187,7 +187,7 @@ set shiftround    " round indent to multiple of shiftwidth with > and <
 set autoindent    " copy indent from current line when starting a new line
 set copyindent    " copy the structure of the existing lines indent when
                   " autoindenting a new line
-if v:version >= 704 && has("patch338")
+if v:version >= 704 && has('patch338')
   set breakindent " every wrapped line will continue visually indented
 endif
 
@@ -198,12 +198,12 @@ set autoread            " automatically read the changed contents
 " store cursor, folds, slash, unix on view
 set viewoptions=cursor,folds,slash,unix
 " change default view directory
-let &viewdir=$MY_VIMRUNTIME."/.view"
+let &viewdir=$MY_VIMRUNTIME.'/.view'
 " save and restore the cursor position and folding level
 function! s:is_view_available() " {{{
   if !&buflisted || &buftype !=# ''
     return 0
-  elseif !filewritable(expand("%:p"))
+  elseif !filewritable(expand('%:p'))
     return 0
   endif
   return 1
@@ -222,17 +222,17 @@ autocmd MyAutoCmd BufWritePost,BufWinLeave ?* call s:mkview()
 autocmd MyAutoCmd BufWinEnter ?* call s:loadview()
 
 " use clipboard register
-if has("unnamedplus") || has("nvim")
+if has('unnamedplus') || has('nvim')
   set clipboard=unnamedplus,unnamed
 else
   set clipboard=unnamed
 endif
 
 " keep undo history on undofile
-if has("persistent_undo")
-  let &undodir=$MY_VIMRUNTIME."/.undo"
+if has('persistent_undo')
+  let &undodir=$MY_VIMRUNTIME.'/.undo'
   if !isdirectory(&undodir)
-    call mkdir(&undodir, "p", 0700)
+    call mkdir(&undodir, 'p', 0700)
   endif
   set undofile
 endif
@@ -300,7 +300,7 @@ set completeopt=menu,longest
 set complete=.            " don't complete from other buffer
 set pumheight=20          " height of popup menu
 set showfulltag           " show both the tag name and the search pattern
-if has("patch-7.4.314")
+if has('patch-7.4.314')
   " don't give ins-completion-menu messages
   set shortmess+=c
 endif
@@ -311,7 +311,7 @@ if v:version >= 703
   set colorcolumn=80
 endif
 
-if has("multi_byte")
+if has('multi_byte')
   set listchars=tab:»-,trail:-,extends:»,precedes:«,nbsp:%,eol:$
 else
   set listchars=tab:>-,trail:-,extends:>,precedes:<,nbsp:%,eol:$
@@ -391,7 +391,7 @@ nnoremap <silent> <Plug>(my-tab)q :<C-u>tabclose<CR>
 nnoremap <silent> <Plug>(my-tab)n :<C-u>tabnext<CR>
 nnoremap <silent> <Plug>(my-tab)p :<C-u>tabprevious<CR>
 for s:n in range(1, 9)
-  execute "nnoremap <silent> <Plug>(my-tab)" . s:n  ":<C-u>tabnext" . s:n . "<CR>"
+  execute 'nnoremap <silent> <Plug>(my-tab)' . s:n  ':<C-u>tabnext' . s:n . '<CR>'
 endfor
 unlet s:n
 
@@ -406,34 +406,34 @@ nnoremap <silent> <Plug>(my-switch)p :<C-u>setl paste! paste?<CR>
 nnoremap <silent> <Plug>(my-switch)b :<C-u>setl scrollbind! scrollbind?<CR>
 nnoremap <silent> <Plug>(my-switch)y :call <SID>toggle_syntax()<CR>
 function! s:toggle_syntax()
-  if exists("g:syntax_on")
+  if exists('g:syntax_on')
     syntax off
     redraw
-    echo "syntax off"
+    echo 'syntax off'
   else
     syntax on
     redraw
-    echo "syntax on"
+    echo 'syntax on'
   endif
 endfunction
 " }}}
 
 " macros {{{
 
-" save the file as root with "sudo"
+" save the file as root with 'sudo"
 cabbr w!! w !sudo tee > /dev/null %
 
 " reload vimrc with <Leader><Leader>r {{{
-if has("vim_starting")
+if has('vim_starting')
   function s:reload_vimrc()
-    execute "source" $MYVIMRC
-    if has("gui_running")
-      execute "source" $MYGVIMRC
+    execute 'source' $MYVIMRC
+    if has('gui_running')
+      execute 'source' $MYGVIMRC
     endif
-    if &filetype ==# "vim"
+    if &filetype ==# 'vim'
       doautocmd FileType
     endif
-    redraw | echo "vimrc has reloaded."
+    redraw | echo 'vimrc has reloaded.'
   endfunction
 endif
 nnoremap <silent> <Leader><Leader>r :<C-u>call <SID>reload_vimrc()<CR>
@@ -441,25 +441,25 @@ nnoremap <silent> <Leader><Leader>r :<C-u>call <SID>reload_vimrc()<CR>
 
 " source/reload current vimscript file " {{{
 function! s:source_current_vimscript()
-  if &filetype !=# "vim"
+  if &filetype !=# 'vim'
     return
   endif
-  if s:load_source(expand("%:p"))
-    redraw | echo expand("%:t") "has sourced."
+  if s:load_source(expand('%:p'))
+    redraw | echo expand('%:t') . 'has sourced.'
   endif
 endfunction
 " }}}
 
 " automatically create missing directories {{{
-autocmd MyAutoCmd BufWritePre * call s:makedirs(expand("<afile>:p:h"), v:cmdbang)
+autocmd MyAutoCmd BufWritePre * call s:makedirs(expand('<afile>:p:h'), v:cmdbang)
 function! s:makedirs(dir, force)
   if !isdirectory(a:dir)
-    if a:force || input(printf("'%s' does not exist. Create? [y/N]", a:dir)) =~? "^y\%[es]$"
-      if v:version < 703 || (v:version == 703 && !has("patch177"))
+    if a:force || input(printf('"%s" does not exist. Create? [y/N]', a:dir)) =~? '^y\%[es]$'
+      if v:version < 703 || (v:version == 703 && !has('patch177'))
         " ref: http://ftp.vim.org/vim/patches/7.3/7.3.177
-        call mkdir(iconv(a:dir, &encoding, &termencoding), "p")
+        call mkdir(iconv(a:dir, &encoding, &termencoding), 'p')
       else
-        call mkdir(a:dir, "p")
+        call mkdir(a:dir, 'p')
       endif
     endif
   endif
@@ -467,31 +467,31 @@ endfunction
 " }}}
 
 " automatically change working directory on vim enter {{{
-"autocmd MyAutoCmd VimEnter * call s:workon(expand("<afile>"), 1)
+"autocmd MyAutoCmd VimEnter * call s:workon(expand('<afile>'), 1)
 function! s:workon(dir, bang)
-  let dir = (a:dir ==# "" ? expand("%") : a:dir)
+  let dir = (a:dir ==# '' ? expand('%') : a:dir)
   " convert filename to directory if required
   if filereadable(dir)
-    let dir = fnamemodify(expand(dir),":p:h")
+    let dir = fnamemodify(expand(dir),':p:h')
   else
-    let dir = fnamemodify(dir, ":p")
+    let dir = fnamemodify(dir, ':p')
   endif
   " change directory to specified directory
   if isdirectory(dir)
-    execute "cd " . fnameescape(dir)
-    if a:bang ==# ""
-        redraw | echo "Working on: ".dir
+    execute 'cd ' . fnameescape(dir)
+    if a:bang ==# ''
+        redraw | echo 'Working on: '.dir
     endif
   endif
 endfunction
-command! -nargs=? -complete=dir -bang Workon call s:workon("<args>", "<bang>")
+command! -nargs=? -complete=dir -bang Workon call s:workon('<args>', '<bang>')
 " }}}
 
 " toggle quickfix window {{{
 function! s:toggle_qf()
-  let nwin = winnr("$")
+  let nwin = winnr('$')
   cclose
-  if nwin == winnr("$")
+  if nwin == winnr('$')
     cwindow
   endif
 endfunction
@@ -512,36 +512,36 @@ call s:highlight_zenkaku_spaces()
 " }}}
 
 " plugins {{{
-let s:remote_bundle_root = $MY_VIMRUNTIME . "/bundle"
-let s:neobundle_root = s:remote_bundle_root . "/neobundle.vim"
+let s:remote_bundle_root = $MY_VIMRUNTIME . '/bundle'
+let s:neobundle_root = s:remote_bundle_root . '/neobundle.vim'
 
 function! s:call_neobundle() abort
   call neobundle#begin(s:remote_bundle_root)
   if neobundle#load_cache()
-    call s:load_source($MY_VIMRUNTIME . "/rc/neobundle.define.vim")
+    call s:load_source($MY_VIMRUNTIME . '/rc/neobundle.define.vim')
     NeoBundleSaveCache
   endif
-  call s:load_source($MY_VIMRUNTIME . "/rc/neobundle.config.vim")
+  call s:load_source($MY_VIMRUNTIME . '/rc/neobundle.config.vim')
   call neobundle#end()
-  if !has("vim_starting")
-    call neobundle#call_hook("on_source")
+  if !has('vim_starting')
+    call neobundle#call_hook('on_source')
   endif
 endfunction
-if !filereadable(s:neobundle_root . "/plugin/neobundle.vim")
+if !filereadable(s:neobundle_root . '/plugin/neobundle.vim')
   function! s:install_neobundle() abort
-    let url = "https://github.com/Shougo/neobundle.vim"
-    redraw | echo "Installing neobundle.vim ..."
-    call system("git clone " . url . " " . s:neobundle_root)
-    execute "set runtimepath+=" . s:neobundle_root
+    let url = 'https://github.com/Shougo/neobundle.vim'
+    redraw | echo 'Installing neobundle.vim ...'
+    call system('git clone ' . url . ' ' . s:neobundle_root)
+    execute 'set runtimepath+=' . s:neobundle_root
     call s:call_neobundle()
     redraw
-    echo "Done. Now run :NeoBundleInstall! to install missing plugins."
+    echo 'Done. Now run :NeoBundleInstall! to install missing plugins.'
   endfunction
   command! InstallNeoBundle call s:install_neobundle()
-  redraw | echo "Need plugins? Use :InstallNeoBundle"
+  redraw | echo 'Need plugins? Use :InstallNeoBundle'
 else
-  if has("vim_starting")
-    execute "set runtimepath+=" . s:neobundle_root
+  if has('vim_starting')
+    execute 'set runtimepath+=' . s:neobundle_root
   endif
   call s:call_neobundle()
 endif
@@ -553,10 +553,10 @@ syntax on
 let g:hybrid_use_Xresources = 1
 colorscheme hybrid
 
-" Enable "Man" command even for other filetypes
+" Enable 'Man' command even for other filetypes
 runtime ftplugin/man.vim
 
-call s:load_source(expand("~/.vimrc.local"))
+call s:load_source(expand('~/.vimrc.local'))
 " }}}
 
 " vim:set et ts=2 sts=2 sw=2 tw=0 fdm=marker ft=vim:
